-- Postgres-skjema for Nordavind (F1 i docs/POSTGRES.md).
-- Oversatt fra SQLite-skjemaet med disse bevisste endringene:
--   * INTEGER-flagg -> boolean, TIMESTAMP -> timestamptz (UTC), BLOB -> bytea,
--     REAL -> double precision, AUTOINCREMENT -> identity.
--   * Døde kolonner er utelatt (agents.category + oppdrags-feltene;
--     mission_activity BEHOLDES - brukes av spinup).
--   * FTS5-tabellen erstattes av en tsvector-kolonne på knowledge_notes
--     (norsk config) med GIN-indeks; synken skjer eksplisitt i kode som før.
--   * embedding TEXT(JSON) -> vector(4096); tomme embeddings blir NULL.
--     Ingen vektorindeks ennå - eksakt søk er raskt nok (se planen).

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS tenants (
    id         text PRIMARY KEY,
    name       text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
    id         text PRIMARY KEY,
    tenant_id  text NOT NULL REFERENCES tenants(id),
    email      text NOT NULL UNIQUE,
    role       text NOT NULL DEFAULT 'member',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS login_codes (
    email      text NOT NULL,
    code       text NOT NULL,
    expires_at timestamptz NOT NULL,
    used       boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS sessions (
    token      text PRIMARY KEY,
    user_id    text NOT NULL REFERENCES users(id),
    expires_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS usage_events (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         text NOT NULL DEFAULT '',
    user_id           text NOT NULL DEFAULT '',
    model             text NOT NULL,
    source            text NOT NULL DEFAULT 'chat',
    prompt_tokens     bigint NOT NULL,
    completion_tokens bigint NOT NULL,
    cost_usd          double precision NOT NULL,
    searches          bigint NOT NULL DEFAULT 0,
    duration_ms       bigint NOT NULL DEFAULT 0,
    created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_usage_tenant_day ON usage_events (tenant_id, created_at);
-- Kilde-kolonnen kom etter tabellen (PR #9) — idempotent påfyll for baser fra før.
ALTER TABLE usage_events ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'chat';

CREATE TABLE IF NOT EXISTS chats (
    id             text PRIMARY KEY,
    tenant_id      text NOT NULL,
    user_id        text NOT NULL,
    title          text NOT NULL,
    agent_id       text NOT NULL DEFAULT '',
    kind           text NOT NULL DEFAULT 'chat',
    dashboard_spec text NOT NULL DEFAULT '{"components":[]}',
    folder_id      text NOT NULL DEFAULT '',
    summary        text NOT NULL DEFAULT '',
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_chats_user ON chats (user_id, updated_at);
-- Sammendrags-kolonnen kom etter tabellen — idempotent påfyll for eldre baser.
ALTER TABLE chats ADD COLUMN IF NOT EXISTS summary text NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS chat_messages (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id    text NOT NULL REFERENCES chats(id),
    role       text NOT NULL,
    content    text NOT NULL,
    sources    text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_messages_chat ON chat_messages (chat_id, id);

CREATE TABLE IF NOT EXISTS connections (
    id         text PRIMARY KEY,
    tenant_id  text NOT NULL REFERENCES tenants(id),
    name       text NOT NULL,
    driver     text NOT NULL,
    creds_enc  bytea NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS connection_tables (
    connection_id text NOT NULL REFERENCES connections(id),
    name          text NOT NULL,
    description   text NOT NULL DEFAULT '',
    PRIMARY KEY (connection_id, name)
);

CREATE TABLE IF NOT EXISTS connection_columns (
    connection_id text NOT NULL,
    table_name    text NOT NULL,
    column_name   text NOT NULL,
    description   text NOT NULL DEFAULT '',
    col_type      text NOT NULL DEFAULT '',
    PRIMARY KEY (connection_id, table_name, column_name)
);

CREATE TABLE IF NOT EXISTS connection_access (
    connection_id text NOT NULL,
    table_name    text NOT NULL,
    user_id       text NOT NULL,
    PRIMARY KEY (connection_id, table_name, user_id)
);

CREATE TABLE IF NOT EXISTS connection_links (
    connection_id text NOT NULL,
    from_table    text NOT NULL,
    from_column   text NOT NULL,
    to_table      text NOT NULL,
    to_column     text NOT NULL,
    PRIMARY KEY (connection_id, from_table, from_column, to_table, to_column)
);

CREATE TABLE IF NOT EXISTS connection_views (
    connection_id text NOT NULL,
    name          text NOT NULL,
    sql_text      text NOT NULL,
    description   text NOT NULL DEFAULT '',
    PRIMARY KEY (connection_id, name)
);

CREATE TABLE IF NOT EXISTS corrections (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  text NOT NULL,
    user_id    text NOT NULL,
    chat_id    text NOT NULL DEFAULT '',
    answer     text NOT NULL,
    correction text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_corrections_tenant ON corrections (tenant_id, created_at);

-- Uten: category + oppdrags-feltene (utelatt med vilje, se migrerings-notatet).
CREATE TABLE IF NOT EXISTS agents (
    id                text PRIMARY KEY,
    tenant_id         text NOT NULL,
    user_id           text NOT NULL,
    name              text NOT NULL,
    task              text NOT NULL,
    connection_id     text NOT NULL DEFAULT '',
    schedule_label    text NOT NULL DEFAULT '',
    interval_seconds  bigint NOT NULL DEFAULT 86400,
    daily_token_limit bigint NOT NULL DEFAULT 0,
    write_access      boolean NOT NULL DEFAULT false,
    enabled           boolean NOT NULL DEFAULT true,
    run_time          text NOT NULL DEFAULT '',
    next_run_at       timestamptz,
    last_run_at       timestamptz,
    chat_id           text NOT NULL DEFAULT '',
    push_enabled      boolean NOT NULL DEFAULT false,
    mission_activity  text NOT NULL DEFAULT '',
    plan              text NOT NULL DEFAULT '',
    plan_status       text NOT NULL DEFAULT '',
    plan_error        text NOT NULL DEFAULT '',
    plan_built_at     timestamptz,
    last_snapshot     text NOT NULL DEFAULT '',
    last_snapshot_at  timestamptz,
    personality       text NOT NULL DEFAULT '',
    response_seen_at  timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_agents_user ON agents (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_agents_due ON agents (enabled, next_run_at);

CREATE TABLE IF NOT EXISTS agent_runs (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id    text NOT NULL,
    started_at  timestamptz NOT NULL DEFAULT now(),
    status      text NOT NULL,
    output      text NOT NULL DEFAULT '',
    tokens_used bigint NOT NULL DEFAULT 0,
    error       text NOT NULL DEFAULT '',
    alert       boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_runs_agent ON agent_runs (agent_id, started_at);

CREATE TABLE IF NOT EXISTS knowledge_nodes (
    id         text PRIMARY KEY,
    tenant_id  text NOT NULL,
    type       text NOT NULL DEFAULT 'term',
    title      text NOT NULL,
    summary    text NOT NULL,
    status     text NOT NULL DEFAULT 'pending',
    chat_id    text NOT NULL DEFAULT '',
    user_id    text NOT NULL DEFAULT '',
    embedding  vector(4096),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_knodes_tenant ON knowledge_nodes (tenant_id, status);

CREATE TABLE IF NOT EXISTS knowledge_edges (
    tenant_id text NOT NULL,
    from_id   text NOT NULL,
    to_id     text NOT NULL,
    relation  text NOT NULL DEFAULT '',
    PRIMARY KEY (from_id, to_id, relation)
);
CREATE INDEX IF NOT EXISTS idx_kedges_from ON knowledge_edges (from_id);
CREATE INDEX IF NOT EXISTS idx_kedges_to ON knowledge_edges (to_id);

CREATE TABLE IF NOT EXISTS widgets (
    id         text PRIMARY KEY,
    tenant_id  text NOT NULL,
    user_id    text NOT NULL,
    slug       text NOT NULL,
    title      text NOT NULL DEFAULT '',
    spec       text NOT NULL DEFAULT '{}',
    saved      boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_widgets_slug ON widgets (user_id, slug);

CREATE TABLE IF NOT EXISTS mail_accounts (
    id         text PRIMARY KEY,
    user_id    text NOT NULL UNIQUE,
    email      text NOT NULL,
    imap_host  text NOT NULL,
    imap_port  bigint NOT NULL DEFAULT 993,
    smtp_host  text NOT NULL,
    smtp_port  bigint NOT NULL DEFAULT 587,
    pass_enc   bytea NOT NULL,
    signature  text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS document_chunks (
    id         text PRIMARY KEY,
    node_id    text NOT NULL,
    tenant_id  text NOT NULL,
    ordinal    bigint NOT NULL DEFAULT 0,
    content    text NOT NULL,
    embedding  vector(4096),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_dchunks_node ON document_chunks (node_id);
CREATE INDEX IF NOT EXISTS idx_dchunks_tenant ON document_chunks (tenant_id);

CREATE TABLE IF NOT EXISTS documents (
    node_id    text PRIMARY KEY,
    tenant_id  text NOT NULL,
    filename   text NOT NULL DEFAULT '',
    raw_text   text NOT NULL DEFAULT '',
    title      text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);

-- fts erstatter FTS5-tabellen: settes eksplisitt ved insert/oppdatering.
CREATE TABLE IF NOT EXISTS knowledge_notes (
    id          text PRIMARY KEY,
    tenant_id   text NOT NULL,
    source_type text NOT NULL DEFAULT 'fact',
    source_id   text NOT NULL DEFAULT '',
    title       text NOT NULL DEFAULT '',
    text        text NOT NULL,
    context     text NOT NULL DEFAULT '',
    status      text NOT NULL DEFAULT 'pending',
    chat_id     text NOT NULL DEFAULT '',
    user_id     text NOT NULL DEFAULT '',
    embedding   vector(4096),
    fts         tsvector,
    hits        bigint NOT NULL DEFAULT 0,
    last_hit_at timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE knowledge_notes ADD COLUMN IF NOT EXISTS hits bigint NOT NULL DEFAULT 0;
ALTER TABLE knowledge_notes ADD COLUMN IF NOT EXISTS last_hit_at timestamptz;
CREATE INDEX IF NOT EXISTS idx_notes_tenant ON knowledge_notes (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_notes_source ON knowledge_notes (source_id);
CREATE INDEX IF NOT EXISTS idx_notes_fts ON knowledge_notes USING GIN (fts);

CREATE TABLE IF NOT EXISTS push_notifications (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  text NOT NULL,
    user_id    text NOT NULL,
    agent_id   text NOT NULL,
    title      text NOT NULL DEFAULT '',
    body       text NOT NULL DEFAULT '',
    sent       boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_push_unsent ON push_notifications (sent, created_at);

CREATE TABLE IF NOT EXISTS employees (
    id          text PRIMARY KEY,
    tenant_id   text NOT NULL,
    name        text NOT NULL,
    role        text NOT NULL DEFAULT '',
    description text NOT NULL DEFAULT '',
    email       text NOT NULL DEFAULT '',
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_employees_tenant ON employees (tenant_id, name);

CREATE TABLE IF NOT EXISTS folders (
    id         text PRIMARY KEY,
    tenant_id  text NOT NULL,
    user_id    text NOT NULL,
    name       text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_folders_user ON folders (user_id, created_at);

CREATE TABLE IF NOT EXISTS export_links (
    id            text PRIMARY KEY,
    tenant_id     text NOT NULL,
    user_id       text NOT NULL,
    title         text NOT NULL DEFAULT '',
    connection_id text NOT NULL DEFAULT '',
    sql_text      text NOT NULL,
    token_hash    text NOT NULL UNIQUE,
    revoked       boolean NOT NULL DEFAULT false,
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_used_at  timestamptz
);
CREATE INDEX IF NOT EXISTS idx_export_links_user ON export_links (user_id, created_at);

CREATE TABLE IF NOT EXISTS m365_accounts (
    user_id     text PRIMARY KEY,
    tenant_id   text NOT NULL,
    email       text NOT NULL DEFAULT '',
    refresh_enc bytea NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS m365_apps (
    tenant_id  text PRIMARY KEY,
    client_id  text NOT NULL,
    secret_enc bytea NOT NULL,
    aad_tenant text NOT NULL DEFAULT 'common',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS onedrive_exports (
    id            text PRIMARY KEY,
    tenant_id     text NOT NULL,
    user_id       text NOT NULL,
    title         text NOT NULL DEFAULT '',
    connection_id text NOT NULL DEFAULT '',
    sql_text      text NOT NULL,
    drive_item_id text NOT NULL,
    web_url       text NOT NULL DEFAULT '',
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_push_at  timestamptz
);
CREATE INDEX IF NOT EXISTS idx_onedrive_user ON onedrive_exports (user_id, created_at);

CREATE TABLE IF NOT EXISTS m365_states (
    state      text PRIMARY KEY,
    tenant_id  text NOT NULL,
    user_id    text NOT NULL,
    expires_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS intent_decisions (
    id         text PRIMARY KEY,
    tenant_id  text NOT NULL,
    user_id    text NOT NULL,
    message    text NOT NULL,
    key        text NOT NULL DEFAULT '',
    method     text NOT NULL,
    candidates text NOT NULL DEFAULT '[]',
    elapsed_ms bigint NOT NULL DEFAULT 0,
    corrected  text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_intent_decisions_created ON intent_decisions (created_at);
